#!/usr/bin/perl -w

print "# generated by vectors.pl\n";

print ".text\n";
print ".align 8\n";

print ".globl alltraps\n";
for (my $i = 0; $i < 256; $i++){
	print ".globl vector$i\n";
	print "vector$i: \n";
	if (!($i == 8 || ($i >= 10 && $i <= 14) || $i == 17)){
		print "	pushq \$0\n";
	}

	print "	pushq \$$i\n";

#	if (!($i == 127)){
		print "	jmp alltraps\n";
#	}	
}

print "\n # vector table \n";
print ".data\n";
print ".globl vectors\n";
print "vectors: \n";
for (my $i = 0; $i < 256; $i++){
	print "	.quad vector$i\n";
}
