vector0: 
 pushq $0
 pushq $0
 jmp isr_entry
vector1: 
 pushq $0
 pushq $1
 jmp isr_entry
vector2: 
 pushq $0
 pushq $2
 jmp isr_entry
vector3: 
 pushq $0
 pushq $3
 jmp isr_entry
vector4: 
 pushq $0
 pushq $4
 jmp isr_entry
vector5: 
 pushq $0
 pushq $5
 jmp isr_entry
vector6: 
 pushq $0
 pushq $6
 jmp isr_entry
vector7: 
 pushq $0
 pushq $7
 jmp isr_entry
vector8: 
 pushq $8
 jmp isr_entry
vector9: 
 pushq $0
 pushq $9
 jmp isr_entry
vector10: 
 pushq $10
 jmp isr_entry
vector11: 
 pushq $11
 jmp isr_entry
vector12: 
 pushq $12
 jmp isr_entry
vector13: 
 pushq $13
 jmp isr_entry
vector14: 
 pushq $14
 jmp isr_entry
vector15: 
 pushq $0
 pushq $15
 jmp isr_entry
vector16: 
 pushq $0
 pushq $16
 jmp isr_entry
vector17: 
 pushq $17
 jmp isr_entry
vector18: 
 pushq $0
 pushq $18
 jmp isr_entry
vector19: 
 pushq $0
 pushq $19
 jmp isr_entry
vector20: 
 pushq $0
 pushq $20
 jmp isr_entry
vector21: 
 pushq $0
 pushq $21
 jmp isr_entry
vector22: 
 pushq $0
 pushq $22
 jmp isr_entry
vector23: 
 pushq $0
 pushq $23
 jmp isr_entry
vector24: 
 pushq $0
 pushq $24
 jmp isr_entry
vector25: 
 pushq $0
 pushq $25
 jmp isr_entry
vector26: 
 pushq $0
 pushq $26
 jmp isr_entry
vector27: 
 pushq $0
 pushq $27
 jmp isr_entry
vector28: 
 pushq $0
 pushq $28
 jmp isr_entry
vector29: 
 pushq $0
 pushq $29
 jmp isr_entry
vector30: 
 pushq $0
 pushq $30
 jmp isr_entry
vector31: 
 pushq $0
 pushq $31
 jmp isr_entry
vector32: 
 pushq $0
 pushq $32
 jmp isr_entry
vector33: 
 pushq $0
 pushq $33
 jmp isr_entry
vector34: 
 pushq $0
 pushq $34
 jmp isr_entry
vector35: 
 pushq $0
 pushq $35
 jmp isr_entry
vector36: 
 pushq $0
 pushq $36
 jmp isr_entry
vector37: 
 pushq $0
 pushq $37
 jmp isr_entry
vector38: 
 pushq $0
 pushq $38
 jmp isr_entry
vector39: 
 pushq $0
 pushq $39
 jmp isr_entry
vector40: 
 pushq $0
 pushq $40
 jmp isr_entry
vector41: 
 pushq $0
 pushq $41
 jmp isr_entry
vector42: 
 pushq $0
 pushq $42
 jmp isr_entry
vector43: 
 pushq $0
 pushq $43
 jmp isr_entry
vector44: 
 pushq $0
 pushq $44
 jmp isr_entry
vector45: 
 pushq $0
 pushq $45
 jmp isr_entry
vector46: 
 pushq $0
 pushq $46
 jmp isr_entry
vector47: 
 pushq $0
 pushq $47
 jmp isr_entry
vector48: 
 pushq $0
 pushq $48
 jmp isr_entry
vector49: 
 pushq $0
 pushq $49
 jmp isr_entry
vector50: 
 pushq $0
 pushq $50
 jmp isr_entry
vector51: 
 pushq $0
 pushq $51
 jmp isr_entry
vector52: 
 pushq $0
 pushq $52
 jmp isr_entry
vector53: 
 pushq $0
 pushq $53
 jmp isr_entry
vector54: 
 pushq $0
 pushq $54
 jmp isr_entry
vector55: 
 pushq $0
 pushq $55
 jmp isr_entry
vector56: 
 pushq $0
 pushq $56
 jmp isr_entry
vector57: 
 pushq $0
 pushq $57
 jmp isr_entry
vector58: 
 pushq $0
 pushq $58
 jmp isr_entry
vector59: 
 pushq $0
 pushq $59
 jmp isr_entry
vector60: 
 pushq $0
 pushq $60
 jmp isr_entry
vector61: 
 pushq $0
 pushq $61
 jmp isr_entry
vector62: 
 pushq $0
 pushq $62
 jmp isr_entry
vector63: 
 pushq $0
 pushq $63
 jmp isr_entry
vector64: 
 pushq $0
 pushq $64
 jmp isr_entry
vector65: 
 pushq $0
 pushq $65
 jmp isr_entry
vector66: 
 pushq $0
 pushq $66
 jmp isr_entry
vector67: 
 pushq $0
 pushq $67
 jmp isr_entry
vector68: 
 pushq $0
 pushq $68
 jmp isr_entry
vector69: 
 pushq $0
 pushq $69
 jmp isr_entry
vector70: 
 pushq $0
 pushq $70
 jmp isr_entry
vector71: 
 pushq $0
 pushq $71
 jmp isr_entry
vector72: 
 pushq $0
 pushq $72
 jmp isr_entry
vector73: 
 pushq $0
 pushq $73
 jmp isr_entry
vector74: 
 pushq $0
 pushq $74
 jmp isr_entry
vector75: 
 pushq $0
 pushq $75
 jmp isr_entry
vector76: 
 pushq $0
 pushq $76
 jmp isr_entry
vector77: 
 pushq $0
 pushq $77
 jmp isr_entry
vector78: 
 pushq $0
 pushq $78
 jmp isr_entry
vector79: 
 pushq $0
 pushq $79
 jmp isr_entry
vector80: 
 pushq $0
 pushq $80
 jmp isr_entry
vector81: 
 pushq $0
 pushq $81
 jmp isr_entry
vector82: 
 pushq $0
 pushq $82
 jmp isr_entry
vector83: 
 pushq $0
 pushq $83
 jmp isr_entry
vector84: 
 pushq $0
 pushq $84
 jmp isr_entry
vector85: 
 pushq $0
 pushq $85
 jmp isr_entry
vector86: 
 pushq $0
 pushq $86
 jmp isr_entry
vector87: 
 pushq $0
 pushq $87
 jmp isr_entry
vector88: 
 pushq $0
 pushq $88
 jmp isr_entry
vector89: 
 pushq $0
 pushq $89
 jmp isr_entry
vector90: 
 pushq $0
 pushq $90
 jmp isr_entry
vector91: 
 pushq $0
 pushq $91
 jmp isr_entry
vector92: 
 pushq $0
 pushq $92
 jmp isr_entry
vector93: 
 pushq $0
 pushq $93
 jmp isr_entry
vector94: 
 pushq $0
 pushq $94
 jmp isr_entry
vector95: 
 pushq $0
 pushq $95
 jmp isr_entry
vector96: 
 pushq $0
 pushq $96
 jmp isr_entry
vector97: 
 pushq $0
 pushq $97
 jmp isr_entry
vector98: 
 pushq $0
 pushq $98
 jmp isr_entry
vector99: 
 pushq $0
 pushq $99
 jmp isr_entry
vector100: 
 pushq $0
 pushq $100
 jmp isr_entry
vector101: 
 pushq $0
 pushq $101
 jmp isr_entry
vector102: 
 pushq $0
 pushq $102
 jmp isr_entry
vector103: 
 pushq $0
 pushq $103
 jmp isr_entry
vector104: 
 pushq $0
 pushq $104
 jmp isr_entry
vector105: 
 pushq $0
 pushq $105
 jmp isr_entry
vector106: 
 pushq $0
 pushq $106
 jmp isr_entry
vector107: 
 pushq $0
 pushq $107
 jmp isr_entry
vector108: 
 pushq $0
 pushq $108
 jmp isr_entry
vector109: 
 pushq $0
 pushq $109
 jmp isr_entry
vector110: 
 pushq $0
 pushq $110
 jmp isr_entry
vector111: 
 pushq $0
 pushq $111
 jmp isr_entry
vector112: 
 pushq $0
 pushq $112
 jmp isr_entry
vector113: 
 pushq $0
 pushq $113
 jmp isr_entry
vector114: 
 pushq $0
 pushq $114
 jmp isr_entry
vector115: 
 pushq $0
 pushq $115
 jmp isr_entry
vector116: 
 pushq $0
 pushq $116
 jmp isr_entry
vector117: 
 pushq $0
 pushq $117
 jmp isr_entry
vector118: 
 pushq $0
 pushq $118
 jmp isr_entry
vector119: 
 pushq $0
 pushq $119
 jmp isr_entry
vector120: 
 pushq $0
 pushq $120
 jmp isr_entry
vector121: 
 pushq $0
 pushq $121
 jmp isr_entry
vector122: 
 pushq $0
 pushq $122
 jmp isr_entry
vector123: 
 pushq $0
 pushq $123
 jmp isr_entry
vector124: 
 pushq $0
 pushq $124
 jmp isr_entry
vector125: 
 pushq $0
 pushq $125
 jmp isr_entry
vector126: 
 pushq $0
 pushq $126
 jmp isr_entry
vector127: 
 pushq $0
 pushq $127
 jmp isr_entry
vector128: 
 pushq $0
 pushq $128
 jmp isr_entry
vector129: 
 pushq $0
 pushq $129
 jmp isr_entry
vector130: 
 pushq $0
 pushq $130
 jmp isr_entry
vector131: 
 pushq $0
 pushq $131
 jmp isr_entry
vector132: 
 pushq $0
 pushq $132
 jmp isr_entry
vector133: 
 pushq $0
 pushq $133
 jmp isr_entry
vector134: 
 pushq $0
 pushq $134
 jmp isr_entry
vector135: 
 pushq $0
 pushq $135
 jmp isr_entry
vector136: 
 pushq $0
 pushq $136
 jmp isr_entry
vector137: 
 pushq $0
 pushq $137
 jmp isr_entry
vector138: 
 pushq $0
 pushq $138
 jmp isr_entry
vector139: 
 pushq $0
 pushq $139
 jmp isr_entry
vector140: 
 pushq $0
 pushq $140
 jmp isr_entry
vector141: 
 pushq $0
 pushq $141
 jmp isr_entry
vector142: 
 pushq $0
 pushq $142
 jmp isr_entry
vector143: 
 pushq $0
 pushq $143
 jmp isr_entry
vector144: 
 pushq $0
 pushq $144
 jmp isr_entry
vector145: 
 pushq $0
 pushq $145
 jmp isr_entry
vector146: 
 pushq $0
 pushq $146
 jmp isr_entry
vector147: 
 pushq $0
 pushq $147
 jmp isr_entry
vector148: 
 pushq $0
 pushq $148
 jmp isr_entry
vector149: 
 pushq $0
 pushq $149
 jmp isr_entry
vector150: 
 pushq $0
 pushq $150
 jmp isr_entry
vector151: 
 pushq $0
 pushq $151
 jmp isr_entry
vector152: 
 pushq $0
 pushq $152
 jmp isr_entry
vector153: 
 pushq $0
 pushq $153
 jmp isr_entry
vector154: 
 pushq $0
 pushq $154
 jmp isr_entry
vector155: 
 pushq $0
 pushq $155
 jmp isr_entry
vector156: 
 pushq $0
 pushq $156
 jmp isr_entry
vector157: 
 pushq $0
 pushq $157
 jmp isr_entry
vector158: 
 pushq $0
 pushq $158
 jmp isr_entry
vector159: 
 pushq $0
 pushq $159
 jmp isr_entry
vector160: 
 pushq $0
 pushq $160
 jmp isr_entry
vector161: 
 pushq $0
 pushq $161
 jmp isr_entry
vector162: 
 pushq $0
 pushq $162
 jmp isr_entry
vector163: 
 pushq $0
 pushq $163
 jmp isr_entry
vector164: 
 pushq $0
 pushq $164
 jmp isr_entry
vector165: 
 pushq $0
 pushq $165
 jmp isr_entry
vector166: 
 pushq $0
 pushq $166
 jmp isr_entry
vector167: 
 pushq $0
 pushq $167
 jmp isr_entry
vector168: 
 pushq $0
 pushq $168
 jmp isr_entry
vector169: 
 pushq $0
 pushq $169
 jmp isr_entry
vector170: 
 pushq $0
 pushq $170
 jmp isr_entry
vector171: 
 pushq $0
 pushq $171
 jmp isr_entry
vector172: 
 pushq $0
 pushq $172
 jmp isr_entry
vector173: 
 pushq $0
 pushq $173
 jmp isr_entry
vector174: 
 pushq $0
 pushq $174
 jmp isr_entry
vector175: 
 pushq $0
 pushq $175
 jmp isr_entry
vector176: 
 pushq $0
 pushq $176
 jmp isr_entry
vector177: 
 pushq $0
 pushq $177
 jmp isr_entry
vector178: 
 pushq $0
 pushq $178
 jmp isr_entry
vector179: 
 pushq $0
 pushq $179
 jmp isr_entry
vector180: 
 pushq $0
 pushq $180
 jmp isr_entry
vector181: 
 pushq $0
 pushq $181
 jmp isr_entry
vector182: 
 pushq $0
 pushq $182
 jmp isr_entry
vector183: 
 pushq $0
 pushq $183
 jmp isr_entry
vector184: 
 pushq $0
 pushq $184
 jmp isr_entry
vector185: 
 pushq $0
 pushq $185
 jmp isr_entry
vector186: 
 pushq $0
 pushq $186
 jmp isr_entry
vector187: 
 pushq $0
 pushq $187
 jmp isr_entry
vector188: 
 pushq $0
 pushq $188
 jmp isr_entry
vector189: 
 pushq $0
 pushq $189
 jmp isr_entry
vector190: 
 pushq $0
 pushq $190
 jmp isr_entry
vector191: 
 pushq $0
 pushq $191
 jmp isr_entry
vector192: 
 pushq $0
 pushq $192
 jmp isr_entry
vector193: 
 pushq $0
 pushq $193
 jmp isr_entry
vector194: 
 pushq $0
 pushq $194
 jmp isr_entry
vector195: 
 pushq $0
 pushq $195
 jmp isr_entry
vector196: 
 pushq $0
 pushq $196
 jmp isr_entry
vector197: 
 pushq $0
 pushq $197
 jmp isr_entry
vector198: 
 pushq $0
 pushq $198
 jmp isr_entry
vector199: 
 pushq $0
 pushq $199
 jmp isr_entry
vector200: 
 pushq $0
 pushq $200
 jmp isr_entry
vector201: 
 pushq $0
 pushq $201
 jmp isr_entry
vector202: 
 pushq $0
 pushq $202
 jmp isr_entry
vector203: 
 pushq $0
 pushq $203
 jmp isr_entry
vector204: 
 pushq $0
 pushq $204
 jmp isr_entry
vector205: 
 pushq $0
 pushq $205
 jmp isr_entry
vector206: 
 pushq $0
 pushq $206
 jmp isr_entry
vector207: 
 pushq $0
 pushq $207
 jmp isr_entry
vector208: 
 pushq $0
 pushq $208
 jmp isr_entry
vector209: 
 pushq $0
 pushq $209
 jmp isr_entry
vector210: 
 pushq $0
 pushq $210
 jmp isr_entry
vector211: 
 pushq $0
 pushq $211
 jmp isr_entry
vector212: 
 pushq $0
 pushq $212
 jmp isr_entry
vector213: 
 pushq $0
 pushq $213
 jmp isr_entry
vector214: 
 pushq $0
 pushq $214
 jmp isr_entry
vector215: 
 pushq $0
 pushq $215
 jmp isr_entry
vector216: 
 pushq $0
 pushq $216
 jmp isr_entry
vector217: 
 pushq $0
 pushq $217
 jmp isr_entry
vector218: 
 pushq $0
 pushq $218
 jmp isr_entry
vector219: 
 pushq $0
 pushq $219
 jmp isr_entry
vector220: 
 pushq $0
 pushq $220
 jmp isr_entry
vector221: 
 pushq $0
 pushq $221
 jmp isr_entry
vector222: 
 pushq $0
 pushq $222
 jmp isr_entry
vector223: 
 pushq $0
 pushq $223
 jmp isr_entry
vector224: 
 pushq $0
 pushq $224
 jmp isr_entry
vector225: 
 pushq $0
 pushq $225
 jmp isr_entry
vector226: 
 pushq $0
 pushq $226
 jmp isr_entry
vector227: 
 pushq $0
 pushq $227
 jmp isr_entry
vector228: 
 pushq $0
 pushq $228
 jmp isr_entry
vector229: 
 pushq $0
 pushq $229
 jmp isr_entry
vector230: 
 pushq $0
 pushq $230
 jmp isr_entry
vector231: 
 pushq $0
 pushq $231
 jmp isr_entry
vector232: 
 pushq $0
 pushq $232
 jmp isr_entry
vector233: 
 pushq $0
 pushq $233
 jmp isr_entry
vector234: 
 pushq $0
 pushq $234
 jmp isr_entry
vector235: 
 pushq $0
 pushq $235
 jmp isr_entry
vector236: 
 pushq $0
 pushq $236
 jmp isr_entry
vector237: 
 pushq $0
 pushq $237
 jmp isr_entry
vector238: 
 pushq $0
 pushq $238
 jmp isr_entry
vector239: 
 pushq $0
 pushq $239
 jmp isr_entry
vector240: 
 pushq $0
 pushq $240
 jmp isr_entry
vector241: 
 pushq $0
 pushq $241
 jmp isr_entry
vector242: 
 pushq $0
 pushq $242
 jmp isr_entry
vector243: 
 pushq $0
 pushq $243
 jmp isr_entry
vector244: 
 pushq $0
 pushq $244
 jmp isr_entry
vector245: 
 pushq $0
 pushq $245
 jmp isr_entry
vector246: 
 pushq $0
 pushq $246
 jmp isr_entry
vector247: 
 pushq $0
 pushq $247
 jmp isr_entry
vector248: 
 pushq $0
 pushq $248
 jmp isr_entry
vector249: 
 pushq $0
 pushq $249
 jmp isr_entry
vector250: 
 pushq $0
 pushq $250
 jmp isr_entry
vector251: 
 pushq $0
 pushq $251
 jmp isr_entry
vector252: 
 pushq $0
 pushq $252
 jmp isr_entry
vector253: 
 pushq $0
 pushq $253
 jmp isr_entry
vector254: 
 pushq $0
 pushq $254
 jmp isr_entry
vector255: 
 pushq $0
 pushq $255
 jmp isr_entry
.globl vectors
vectors: 
.quad vector0
.quad vector1
.quad vector2
.quad vector3
.quad vector4
.quad vector5
.quad vector6
.quad vector7
.quad vector8
.quad vector9
.quad vector10
.quad vector11
.quad vector12
.quad vector13
.quad vector14
.quad vector15
.quad vector16
.quad vector17
.quad vector18
.quad vector19
.quad vector20
.quad vector21
.quad vector22
.quad vector23
.quad vector24
.quad vector25
.quad vector26
.quad vector27
.quad vector28
.quad vector29
.quad vector30
.quad vector31
.quad vector32
.quad vector33
.quad vector34
.quad vector35
.quad vector36
.quad vector37
.quad vector38
.quad vector39
.quad vector40
.quad vector41
.quad vector42
.quad vector43
.quad vector44
.quad vector45
.quad vector46
.quad vector47
.quad vector48
.quad vector49
.quad vector50
.quad vector51
.quad vector52
.quad vector53
.quad vector54
.quad vector55
.quad vector56
.quad vector57
.quad vector58
.quad vector59
.quad vector60
.quad vector61
.quad vector62
.quad vector63
.quad vector64
.quad vector65
.quad vector66
.quad vector67
.quad vector68
.quad vector69
.quad vector70
.quad vector71
.quad vector72
.quad vector73
.quad vector74
.quad vector75
.quad vector76
.quad vector77
.quad vector78
.quad vector79
.quad vector80
.quad vector81
.quad vector82
.quad vector83
.quad vector84
.quad vector85
.quad vector86
.quad vector87
.quad vector88
.quad vector89
.quad vector90
.quad vector91
.quad vector92
.quad vector93
.quad vector94
.quad vector95
.quad vector96
.quad vector97
.quad vector98
.quad vector99
.quad vector100
.quad vector101
.quad vector102
.quad vector103
.quad vector104
.quad vector105
.quad vector106
.quad vector107
.quad vector108
.quad vector109
.quad vector110
.quad vector111
.quad vector112
.quad vector113
.quad vector114
.quad vector115
.quad vector116
.quad vector117
.quad vector118
.quad vector119
.quad vector120
.quad vector121
.quad vector122
.quad vector123
.quad vector124
.quad vector125
.quad vector126
.quad vector127
.quad vector128
.quad vector129
.quad vector130
.quad vector131
.quad vector132
.quad vector133
.quad vector134
.quad vector135
.quad vector136
.quad vector137
.quad vector138
.quad vector139
.quad vector140
.quad vector141
.quad vector142
.quad vector143
.quad vector144
.quad vector145
.quad vector146
.quad vector147
.quad vector148
.quad vector149
.quad vector150
.quad vector151
.quad vector152
.quad vector153
.quad vector154
.quad vector155
.quad vector156
.quad vector157
.quad vector158
.quad vector159
.quad vector160
.quad vector161
.quad vector162
.quad vector163
.quad vector164
.quad vector165
.quad vector166
.quad vector167
.quad vector168
.quad vector169
.quad vector170
.quad vector171
.quad vector172
.quad vector173
.quad vector174
.quad vector175
.quad vector176
.quad vector177
.quad vector178
.quad vector179
.quad vector180
.quad vector181
.quad vector182
.quad vector183
.quad vector184
.quad vector185
.quad vector186
.quad vector187
.quad vector188
.quad vector189
.quad vector190
.quad vector191
.quad vector192
.quad vector193
.quad vector194
.quad vector195
.quad vector196
.quad vector197
.quad vector198
.quad vector199
.quad vector200
.quad vector201
.quad vector202
.quad vector203
.quad vector204
.quad vector205
.quad vector206
.quad vector207
.quad vector208
.quad vector209
.quad vector210
.quad vector211
.quad vector212
.quad vector213
.quad vector214
.quad vector215
.quad vector216
.quad vector217
.quad vector218
.quad vector219
.quad vector220
.quad vector221
.quad vector222
.quad vector223
.quad vector224
.quad vector225
.quad vector226
.quad vector227
.quad vector228
.quad vector229
.quad vector230
.quad vector231
.quad vector232
.quad vector233
.quad vector234
.quad vector235
.quad vector236
.quad vector237
.quad vector238
.quad vector239
.quad vector240
.quad vector241
.quad vector242
.quad vector243
.quad vector244
.quad vector245
.quad vector246
.quad vector247
.quad vector248
.quad vector249
.quad vector250
.quad vector251
.quad vector252
.quad vector253
.quad vector254
.quad vector255
